#!/usr/bin/sudo bash
#NOTE: cannot call this utility 'reset', that already exists as a bash utility 

set -e

#first have to identify which tcpborphserver called this funtion
#because we need to get the associated pci address

#take my PPID and search for it's PPID = grandparent pid
GRANDPARENT_PID=$(ps -fp $PPID | awk "/$PPID/"' { print $3 } ')
ARGS=$(ps -o args -p ${GRANDPARENT_PID})
#TODO the line below has a potential bug - if the process
#was started without a space before the arg, this may lead to issue with cut's space delimiter
#check this i.e. there will be no space e.g. -d/dev/...
DEVICE=$(echo ${ARGS#*"-d"} | xargs | cut -d ' ' -f1)

kcpmsg ${DEVICE}

#remove substring "user" to get path
PCIPATH=${DEVICE%"user"}

kcpmsg "about to reset alveo at ${PCIPATH}"

PORT=$(echo ${ARGS#*"-p"} | xargs | cut -d ' ' -f1)

##need to unmap the fpga - simply issue empty ?progdev
##kcpcmd -q -s :${PORT} progdev
## TODO REMOVE ABOVE - DON'T unmap - this reset is usually issued
# after the fpga has been programmed, unampping would not make sense here

test -e ${PCIPATH}/pci/remove && echo 1 > ${PCIPATH}/pci/remove && sleep 1 && echo 1 > /sys/bus/pci/rescan

#wait after reset
sleep 0.5

SERIAL=$(/opt/alveo/alveo-utils/alveo-serial ${DEVICE})
kcpmsg "alveo serial ${SERIAL}"

#update the serial number since it won't be available on first tcpbs launch (cms not up yet)
kcpcmd -q -s :${PORT} version add alveo-serial ${SERIAL}


#exit 0
#do not exit with 0, this allows failed test -e to push 1 back to caller
