#!/usr/bin/sudo bash

#RvW, SARAO, 2022

set -e

#first have to identify which tcpborphserver called this funtion
#because we need to get the associated pci address

#take my PPID and search for it's PPID = grandparent pid
GRANDPARENT_PID=$(ps -fp $PPID | awk "/$PPID/"' { print $3 } ')
ARGS=$(ps -o args -p ${GRANDPARENT_PID})
#TODO the line below has a potential bug - if the process
#was started without a space before the arg, this may lead to issue with cut's space delimiter
#check this i.e. there will be no space e.g. -d/dev/...
DEVICE=$(echo ${ARGS#*"-d"} | xargs | cut -d ' ' -f1)

kcpmsg ${DEVICE}

#remove substring "user" to get path
DEVPATH=${DEVICE%"user"}

PCIPATH=$(readlink -f ${DEVPATH}/pci)

PCIADDR=$(echo ${PCIPATH} | rev | cut -d '/' -f1 | rev)

#assuming file visible with ?listbof
BITFILE="$1"
if test -z ${BITFILE}; then
  BITFILE="tcpborphserver.bit";
  BITPATH="/lib/firmware"
else
  BITPATH="/opt/alveo/alveo-tcpbs-fs"
fi

kcpmsg "about to program alveo at ${PCIADDR} with ${BITFILE} in ${BITPATH}"

cd /opt/alveo/alveo-program/

./alveo-program.sh ${PCIADDR} ${BITPATH}/${BITFILE}

cd -
