#!/usr/bin/sudo bash

#RvW, SARAO, 2022

set -e

echo "WARNING: starting with root permissions!!"

BASE_PORT=7150
#BOF_DIR="/opt/alveo/alveo-fs/"
BOF_DIR="../alveo-tcpbs-fs/"

#export PATH=$PATH:$(pwd)
export PATH=$PATH:$(pwd):${BOF_DIR}

#ALVEOS=$(./alveo-map)
ALVEOS=$(ls /dev/xdma/)

PORT=${BASE_PORT}

for CARD in ${ALVEOS}; do
#  PCIADDR=$(echo ${CARD} | cut -d'/' -f1)
  SERIAL=$(./alveo-serial /dev/xdma/${CARD}/user 2>/dev/null)
  echo $CARD $SERIAL
  #../katcp/tcpborphserver3/tcpborphserver3 -p ${PORT} -l /dev/null -i init-alveo.tbs -d /dev/xdma/${CARD}/user -u $((PORT+1))
  ../katcp/tcpborphserver3/tcpborphserver3 -p ${PORT} -l /dev/null -b ${BOF_DIR} -d /dev/xdma/${CARD}/user -u $((PORT+1))

  #TODO should we wait a bit here?
  sleep 0.5
  ../katcp/cmd/kcpcmd -s localhost:${PORT} version add alveo ${CARD} ${SERIAL}
  ../katcp/cmd/kcpcmd -s localhost:${PORT} process alveo-reset reset\_this\_alveo

  PORT=$((PORT+2))
done
